apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: custom-fastapi-service
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/dockerapi-425716/custom-fastapi/custom-fastapi:latest
          env:
          ports:
            - containerPort: 8080